version: '3.8'
services:

  db:
    image: mariadb:11
    container_name: mariadb-libros
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin123
      MARIADB_DATABASE: librosdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  app:
    build: .
    container_name: libros-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/librosdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123

volumes:
  mariadb-data:
